### ISSUE TITLE
Correct TypeScript definition format

### ISSUE THREAD

**Issue by blakeembrey** [66pix/filename.js#1]
Hey! I come from the linked Typings registry issue and wanted to check it out, and I saw this issue. You don't want to create an "ambient/global" declaration, it needs to be an external module definition. Basically, move everything inside the `declare module '...'` outside and remove it. See more at http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html.

**Comment by faceleg** [comment]
Thanks for taking the time to come here and say these words! Do the  words mean I should change the index.d.ts to look more like this:

``` JS
  export function extension(filename: string): string;
  export function basename(filename: string): string;
  export function removeSuffix(filename: string): string;
  export function removeSuffixWithDelimiter(delimiter: string|number, filename: string): string;
  export function appendSuffix(suffix: string, filename: string): string;
  export function appendSuffixWithDelimiter(suffix: string, delimiter: string|number, filename: string): string;
  export function directoryName(filename: string): string;
```

**Comment by blakeembrey** [comment]
Yes, correct.

**Comment by faceleg** [comment]
I tried this, but now when I try to use the definition file, I get "TS2307: Cannot find module 'filename.js'

**Comment by blakeembrey** [comment]
@faceleg How did you test it?

**Comment by blakeembrey** [comment]
It needs to be using node module resolution in `tsconfig.json`.

**Comment by faceleg** [comment]
I tested it by making a project like:

```
/index.ts
```

```
npm init
npm install --save filename.js
tsc index.ts
```

With the file:

```
/// <reference path="node_modules/filename.js/index.d.ts" />

import filenameJs = require("filename.js");

console.log(filenameJs);
```

**Comment by blakeembrey** [comment]
Don't use a reference, use node module resolution in `tsconfig.json`.

**Comment by blakeembrey** [comment]
Use http://www.typescriptlang.org/docs/handbook/tsconfig.json.html. When you set `commonjs`, it uses node module resolution by default.

**Comment by faceleg** [comment]
You mean like `tsc -m commons`, and removing the reference?

**Comment by blakeembrey** [comment]
Yes. The reference wouldn't be doing anything here anyway. See http://json.schemastore.org/tsconfig and the `moduleResolution` option.

**Comment by faceleg** [comment]
Thank you very much for sticking with me on this.

I'm getting "TS5023: Unknown compiler option 'moduleResolution'"

tsc --version
message TS6029: Version 1.5.3

**Comment by blakeembrey** [comment]
You're using a _really_ old version of `tsc`. Try `>=1.6`. The current version is `1.8`.

**Comment by faceleg** [comment]
Something bung with my system, you're right it compiles with moduleResolution in tsc config.

**Comment by faceleg** [comment]
With the removal of the `declare module "filename.js"` portion of the definition, I no longer get the "external package is not a module" error, but I also no longer get any type hinting in my editor (vim, with tsuquyomi + YCM).

**Comment by blakeembrey** [comment]
I can't comment on the VIM plugin, try using Atom or Sublime Text or VSCode. Have you updated the global TypeScript version too?

**Comment by faceleg** [comment]
@blakeembrey thanks for your help. I think I've solved it by just using @types with typescript 2.0 and enabling the `declaration` flag for the compiler.

**Comment by blakeembrey** [comment]
Ok. I'm still confused by why `@types` comes into this at all. You're providing the definition with the module, you shouldn't be using `@types` at all.

**Comment by faceleg** [comment]
You're right, my comment was confusing. I should have just mentioned the `declarations` flag.
